### ISSUE TITLE
Blazor Template Updates

### ISSUE THREAD

**Issue by capdiem** [masastack/MASA.Template#18]
- [x] `masablazor-server`: a server template with a basic layout #19 
- [x] `masablazor-wasm`: a wasm template with a basic layout #20 
- [x] `masablazor-empty-server`: a empty server template #23 
- [x] `masablazor-empty-wasm`: a empty wasm template #25 
- [x] `masablazor-pro-wasm`: a wasm template with Pro #21 
- [x] `masablazor-pro-server`: a server template with Pro #22
- [x] `masablazor-maui`: a MAUI Blazor template #26
